// ============================================================================
// Transliteration Dashboard — Main input/output panel with char mapping
// ============================================================================

import { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ArrowRightLeft, Copy, Download, Volume2, Sparkles,
  CheckCircle2, Languages, Lightbulb, ChevronRight
} from 'lucide-react';
import toast from 'react-hot-toast';
import PageTransition from '../components/layout/PageTransition';
import GlassCard from '../components/ui/GlassCard';
import { transliterateEngToOdia, transliterateOdiaToEng, getCharacterMapping } from '../utils/transliterate';
import { wordPairs } from '../data/transliterationMap';
import { fadeUp, staggerContainer } from '../utils/animations';

export default function TransliterationPage() {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [direction, setDirection] = useState<'eng-to-odia' | 'odia-to-eng'>('eng-to-odia');
  const [charMappings, setCharMappings] = useState<{ source: string; target: string }[]>([]);
  const [isTyping, setIsTyping] = useState(false);

  // Example suggestions
  const suggestions = direction === 'eng-to-odia'
    ? ['namaskar', 'odisha', 'jagannath', 'bhubaneswar', 'chilika', 'puri']
    : ['ନମସ୍କାର', 'ଓଡ଼ିଶା', 'ଜଗନ୍ନାଥ', 'ପୁରୀ', 'ଚିଲିକା', 'ମହାନଦୀ'];

  const transliterate = useCallback((text: string) => {
    if (!text.trim()) {
      setOutput('');
      setCharMappings([]);
      return;
    }

    setIsTyping(true);
    // Simulate slight delay for "AI processing" feel
    setTimeout(() => {
      const result = direction === 'eng-to-odia'
        ? transliterateEngToOdia(text)
        : transliterateOdiaToEng(text);
      setOutput(result);

      // Get character mapping for the first word
      const firstWord = text.split(/\s+/)[0];
      if (firstWord) {
        setCharMappings(getCharacterMapping(firstWord.toLowerCase(), direction));
      }
      setIsTyping(false);
    }, 150);
  }, [direction]);

  useEffect(() => {
    transliterate(input);
  }, [input, transliterate]);

  const handleSwapDirection = () => {
    const newDirection = direction === 'eng-to-odia' ? 'odia-to-eng' : 'eng-to-odia';
    setDirection(newDirection);
    setInput(output);
    setOutput('');
    setCharMappings([]);
  };

  const handleCopy = () => {
    if (output) {
      navigator.clipboard.writeText(output);
      toast.success('Copied to clipboard!', {
        style: {
          background: '#1e1b3a',
          color: '#fff',
          border: '1px solid rgba(139, 92, 246, 0.3)',
        },
        iconTheme: { primary: '#8b5cf6', secondary: '#fff' },
      });
    }
  };

  const handleDownload = () => {
    if (!output) return;
    const blob = new Blob(
      [`Input (${direction === 'eng-to-odia' ? 'English' : 'Odia'}):\n${input}\n\nOutput (${direction === 'eng-to-odia' ? 'Odia' : 'English'}):\n${output}\n\nGenerated by LinguaSync AI`],
      { type: 'text/plain' }
    );
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'transliteration-result.txt';
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Downloaded!', {
      style: { background: '#1e1b3a', color: '#fff', border: '1px solid rgba(139, 92, 246, 0.3)' },
    });
  };

  const handleSuggestionClick = (s: string) => {
    setInput(s);
  };

  return (
    <PageTransition>
      <div className="min-h-screen pt-24 pb-16">
        <div className="section-container">
          {/* Header */}
          <motion.div
            variants={staggerContainer}
            initial="hidden"
            animate="visible"
            className="text-center mb-10"
          >
            <motion.div variants={fadeUp} className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary-500/10 border border-primary-500/20 mb-4">
              <Languages size={14} className="text-primary-400" />
              <span className="text-sm font-medium text-primary-300">Transliteration Engine</span>
            </motion.div>
            <motion.h1 variants={fadeUp} className="text-3xl sm:text-4xl font-bold text-white mb-3">
              English ↔ Odia <span className="gradient-text-static">Transliterator</span>
            </motion.h1>
            <motion.p variants={fadeUp} className="text-white/40 max-w-xl mx-auto">
              Enter text below and get instant AI-powered transliteration with character mapping.
            </motion.p>
          </motion.div>

          {/* Main transliteration panel */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="max-w-5xl mx-auto"
          >
            <div className="glass-card overflow-hidden">
              {/* Direction bar */}
              <div className="flex items-center justify-between p-4 border-b border-white/[0.06]">
                <div className="flex items-center gap-3">
                  <span className={`px-3 py-1.5 rounded-lg text-sm font-medium ${
                    direction === 'eng-to-odia' ? 'bg-primary-500/10 text-primary-300' : 'bg-cyan-500/10 text-cyan-300'
                  }`}>
                    {direction === 'eng-to-odia' ? 'English' : 'ଓଡ଼ିଆ (Odia)'}
                  </span>
                  <button
                    onClick={handleSwapDirection}
                    className="w-9 h-9 rounded-lg bg-white/[0.04] border border-white/[0.08] flex items-center justify-center text-white/50 hover:text-white hover:bg-white/[0.08] transition-all duration-300 hover:rotate-180"
                  >
                    <ArrowRightLeft size={16} />
                  </button>
                  <span className={`px-3 py-1.5 rounded-lg text-sm font-medium ${
                    direction === 'odia-to-eng' ? 'bg-primary-500/10 text-primary-300' : 'bg-cyan-500/10 text-cyan-300'
                  }`}>
                    {direction === 'eng-to-odia' ? 'ଓଡ଼ିଆ (Odia)' : 'English'}
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  {isTyping && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="flex items-center gap-1.5 text-primary-400 text-xs"
                    >
                      <Sparkles size={12} className="animate-spin-slow" />
                      Processing...
                    </motion.div>
                  )}
                </div>
              </div>

              {/* Input/Output split */}
              <div className="grid grid-cols-1 md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-white/[0.06]">
                {/* Input */}
                <div className="p-6">
                  <label className="text-white/30 text-xs font-medium uppercase tracking-wider mb-2 block">
                    Input
                  </label>
                  <textarea
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder={direction === 'eng-to-odia' ? 'Type English text here...' : 'ଏଠାରେ ଓଡ଼ିଆ ଲେଖନ୍ତୁ...'}
                    className="w-full h-40 bg-transparent text-white text-lg outline-none resize-none placeholder:text-white/15 font-mono"
                  />
                  <div className="flex items-center justify-between mt-2 pt-3 border-t border-white/[0.04]">
                    <span className="text-white/20 text-xs">{input.length} characters</span>
                    {input && (
                      <button
                        onClick={() => { setInput(''); setOutput(''); setCharMappings([]); }}
                        className="text-white/30 hover:text-white/60 text-xs transition-colors"
                      >
                        Clear
                      </button>
                    )}
                  </div>
                </div>

                {/* Output */}
                <div className="p-6 bg-white/[0.01]">
                  <label className="text-white/30 text-xs font-medium uppercase tracking-wider mb-2 block">
                    Output
                  </label>
                  <div className="h-40 overflow-y-auto">
                    <AnimatePresence mode="wait">
                      {output ? (
                        <motion.div
                          key={output}
                          initial={{ opacity: 0, y: 5 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0 }}
                          className="text-lg font-mono text-white"
                        >
                          {output}
                        </motion.div>
                      ) : (
                        <p className="text-white/15 text-lg">
                          {direction === 'eng-to-odia' ? 'ଓଡ଼ିଆ ଫଳାଫଳ ଏଠାରେ...' : 'English result here...'}
                        </p>
                      )}
                    </AnimatePresence>
                  </div>
                  <div className="flex items-center justify-between mt-2 pt-3 border-t border-white/[0.04]">
                    <span className="text-white/20 text-xs">
                      {output ? (
                        <span className="flex items-center gap-1 text-green-400/70">
                          <CheckCircle2 size={12} /> Transliterated
                        </span>
                      ) : 'Awaiting input'}
                    </span>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={handleCopy}
                        disabled={!output}
                        className="p-2 rounded-lg hover:bg-white/[0.06] text-white/30 hover:text-white/70 transition-all disabled:opacity-20 disabled:cursor-not-allowed"
                        title="Copy"
                      >
                        <Copy size={14} />
                      </button>
                      <button
                        onClick={handleDownload}
                        disabled={!output}
                        className="p-2 rounded-lg hover:bg-white/[0.06] text-white/30 hover:text-white/70 transition-all disabled:opacity-20 disabled:cursor-not-allowed"
                        title="Download"
                      >
                        <Download size={14} />
                      </button>
                      <button
                        disabled={!output}
                        className="p-2 rounded-lg hover:bg-white/[0.06] text-white/30 hover:text-white/70 transition-all disabled:opacity-20 disabled:cursor-not-allowed"
                        title="Pronunciation (UI mockup)"
                        onClick={() => toast('🔊 Pronunciation feature coming soon!', {
                          style: { background: '#1e1b3a', color: '#fff', border: '1px solid rgba(139, 92, 246, 0.3)' },
                        })}
                      >
                        <Volume2 size={14} />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Suggestions */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="max-w-5xl mx-auto mt-6"
          >
            <div className="flex items-center gap-2 mb-3">
              <Lightbulb size={14} className="text-amber-400/60" />
              <span className="text-white/30 text-xs font-medium uppercase tracking-wider">Try these examples</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {suggestions.map((s) => (
                <button
                  key={s}
                  onClick={() => handleSuggestionClick(s)}
                  className="px-3 py-1.5 rounded-lg bg-white/[0.03] border border-white/[0.06] text-white/40 hover:text-white/70 hover:bg-white/[0.06] hover:border-white/[0.1] text-sm font-mono transition-all duration-200 flex items-center gap-1"
                >
                  {s} <ChevronRight size={12} />
                </button>
              ))}
            </div>
          </motion.div>

          {/* Character Mapping Visualization */}
          <AnimatePresence>
            {charMappings.length > 0 && (
              <motion.div
                initial={{ opacity: 0, y: 30, height: 0 }}
                animate={{ opacity: 1, y: 0, height: 'auto' }}
                exit={{ opacity: 0, y: 20, height: 0 }}
                transition={{ duration: 0.5 }}
                className="max-w-5xl mx-auto mt-8"
              >
                <GlassCard className="p-6">
                  <h3 className="text-white/60 text-sm font-semibold mb-4 flex items-center gap-2">
                    <Sparkles size={14} className="text-primary-400" />
                    Character-Level Phonetic Mapping
                  </h3>
                  <div className="flex flex-wrap gap-3 items-center justify-center">
                    {charMappings.map((m, i) => (
                      <motion.div
                        key={`${m.source}-${i}`}
                        initial={{ opacity: 0, scale: 0.8, y: 10 }}
                        animate={{ opacity: 1, scale: 1, y: 0 }}
                        transition={{ delay: i * 0.08, duration: 0.3 }}
                        className="flex flex-col items-center gap-1"
                      >
                        <span className="px-3 py-1.5 rounded-lg bg-primary-500/10 border border-primary-500/20 text-primary-300 font-mono text-sm">
                          {m.source}
                        </span>
                        <motion.div
                          animate={{ y: [0, -3, 0] }}
                          transition={{ duration: 1.5, repeat: Infinity, delay: i * 0.1 }}
                          className="text-white/20"
                        >
                          ↓
                        </motion.div>
                        <span className="px-3 py-1.5 rounded-lg bg-cyan-500/10 border border-cyan-500/20 text-cyan-300 font-mono text-lg">
                          {m.target}
                        </span>
                      </motion.div>
                    ))}
                  </div>
                </GlassCard>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Recent word pairs showcase */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.6 }}
            className="max-w-5xl mx-auto mt-10"
          >
            <h3 className="text-white/40 text-sm font-semibold mb-4">Sample Word Pairs from Dataset</h3>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3">
              {wordPairs.slice(0, 10).map((pair, i) => (
                <GlassCard
                  key={pair.english}
                  className="p-3 text-center cursor-pointer"
                  delay={i * 0.04}
                  onClick={() => setInput(direction === 'eng-to-odia' ? pair.english : pair.odia)}
                >
                  <p className="text-white/60 font-mono text-sm">{pair.english}</p>
                  <p className="text-white/15 text-xs my-1">↓</p>
                  <p className="text-cyan-300/80 font-mono text-base">{pair.odia}</p>
                </GlassCard>
              ))}
            </div>
          </motion.div>
        </div>
      </div>
    </PageTransition>
  );
}
